[phases.install]
cmds = [
    "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install uv && uv sync --no-dev --frozen --active",
]

[phases.build]
cmds = ['mkdocs build']

[start]
cmd = ''